/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.standalonemaven;

/**
 *
 * @author teran
 */
public class departamentos extends javax.swing.JFrame {
    
    private static departamentos dept;
    static departamentos getInstance(){
        if(dept == null)
            dept = new departamentos();
        return dept;
    }
    /**
     * Creates new form departamentos
     */
    public departamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDireccionGeneral = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnFinanzas = new javax.swing.JButton();
        btnMarketing = new javax.swing.JButton();
        btnRecursos = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnCalidad = new javax.swing.JButton();
        btnContabilidad = new javax.swing.JButton();
        btnTesoreria = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnPublicidad = new javax.swing.JButton();

        jButton8.setText("jButton8");

        setTitle("Departamentos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Directorio Organizacional");

        btnDireccionGeneral.setText("Direccion General");
        btnDireccionGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionGeneralActionPerformed(evt);
            }
        });

        btnProduccion.setText("Produccion");
        btnProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduccionActionPerformed(evt);
            }
        });

        btnFinanzas.setText("Finanzas");
        btnFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanzasActionPerformed(evt);
            }
        });

        btnMarketing.setText("Marketing");
        btnMarketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarketingActionPerformed(evt);
            }
        });

        btnRecursos.setText("Recursos Humanos");
        btnRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursosActionPerformed(evt);
            }
        });

        btnCompras.setText("Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnCalidad.setText("Calidad");
        btnCalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalidadActionPerformed(evt);
            }
        });

        btnContabilidad.setText("Contabilidad");
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });

        btnTesoreria.setText("Tesoreria");
        btnTesoreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesoreriaActionPerformed(evt);
            }
        });

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnPublicidad.setText("Publicidad");
        btnPublicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProduccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalidad)
                                    .addComponent(btnCompras))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTesoreria))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVentas)
                                    .addComponent(btnPublicidad))
                                .addGap(145, 145, 145))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnFinanzas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMarketing)
                                .addGap(18, 18, 18)
                                .addComponent(btnRecursos)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDireccionGeneral)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnDireccionGeneral)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRecursos)
                        .addComponent(btnMarketing))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinanzas)
                            .addComponent(btnProduccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCompras)
                            .addComponent(btnContabilidad)
                            .addComponent(btnVentas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalidad)
                            .addComponent(btnTesoreria)
                            .addComponent(btnPublicidad))))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduccionActionPerformed
        Produccion produccion = Produccion.getInstance();
        produccion.setVisible(true);
        produccion.requestFocus();
    }//GEN-LAST:event_btnProduccionActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        Compras compras = Compras.getInstance();
        compras.setVisible(true);
        compras.requestFocus();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnCalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalidadActionPerformed
        Calidad calidad = Calidad.getInstance();
        calidad.setVisible(true);
        calidad.requestFocus();
    }//GEN-LAST:event_btnCalidadActionPerformed

    private void btnFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanzasActionPerformed
        Finanzas finanzas = Finanzas.getInstance();
        finanzas.setVisible(true);
        finanzas.requestFocus();
    }//GEN-LAST:event_btnFinanzasActionPerformed

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        Contabilidad contabilidad = Contabilidad.getInstance();
        contabilidad.setVisible(true);
        contabilidad.requestFocus();
    }//GEN-LAST:event_btnContabilidadActionPerformed

    private void btnTesoreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesoreriaActionPerformed
        Tesoreria tesoreria = Tesoreria.getInstance();
        tesoreria.setVisible(true);
        tesoreria.requestFocus();
    }//GEN-LAST:event_btnTesoreriaActionPerformed

    private void btnMarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarketingActionPerformed
        Marketing marketing = Marketing.getInstance();
        marketing.setVisible(true);
        marketing.requestFocus();
    }//GEN-LAST:event_btnMarketingActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        Ventas ventas = Ventas.getInstance();
        ventas.setVisible(true);
        ventas.requestFocus();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnPublicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicidadActionPerformed
        Publicidad publicidad = Publicidad.getInstance();
        publicidad.setVisible(true);
        publicidad.requestFocus();
    }//GEN-LAST:event_btnPublicidadActionPerformed

    private void btnRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursosActionPerformed
        RH rh = RH.getInstance();
        rh.setVisible(true);
        rh.requestFocus();
    }//GEN-LAST:event_btnRecursosActionPerformed

    private void btnDireccionGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionGeneralActionPerformed
        DireccionGeneral direccionGeneral = DireccionGeneral.getInstance();
        direccionGeneral.setVisible(true);
        direccionGeneral.requestFocus();
        
    }//GEN-LAST:event_btnDireccionGeneralActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalidad;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnContabilidad;
    private javax.swing.JButton btnDireccionGeneral;
    private javax.swing.JButton btnFinanzas;
    private javax.swing.JButton btnMarketing;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnPublicidad;
    private javax.swing.JButton btnRecursos;
    private javax.swing.JButton btnTesoreria;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
